# Generated by Django 5.2.10 on 2026-01-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='event_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='ticket_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='ticket_price',
            field=models.PositiveIntegerField(blank=True, help_text='Ticket price in KES', null=True),
        ),
    ]
