# Generated by Django 5.2.10 on 2026-01-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_chef_about_chef_event_datetime_chef_ticket_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='paybill_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
